In [1]:
import pandas as pd
import numpy as np

# 1. Generate Weekly Dates: freq='W' gives us 1 row per week
dates = pd.date_range(start='2019-01-01', end='2025-12-31', freq='D')
steps = np.arange(len(dates))

# 2. Generate Percentage Data
np.random.seed(42)
# Since we have ~52.14 weeks in a year, we adjust the sine wave to match
base_seasonality = np.sin(steps * (2 * np.pi / 365)) * 10 
noise = np.random.normal(0, 3, len(dates))
percentages = np.round(base_seasonality + noise, 1)

df = pd.DataFrame({
    'Date': dates, 'Step': steps, 'Value_Pct': percentages
})

df

           Date  Step  Value_Pct
0    2019-01-01     0        1.5
1    2019-01-02     1       -0.2
2    2019-01-03     2        2.3
3    2019-01-04     3        5.1
4    2019-01-05     4       -0.0
...         ...   ...        ...
2552 2025-12-27  2552        5.1
2553 2025-12-28  2553        0.8
2554 2025-12-29  2554       -2.8
2555 2025-12-30  2555        1.6
2556 2025-12-31  2556       -7.7

[2557 rows x 3 columns]

In [2]:
df['Step'] = np.arange(len(df))
df.tail(10)

           Date  Step  Value_Pct
2547 2025-12-22  2547       -3.1
2548 2025-12-23  2548        1.9
2549 2025-12-24  2549        5.2
2550 2025-12-25  2550       -5.6
2551 2025-12-26  2551       -6.3
2552 2025-12-27  2552        5.1
2553 2025-12-28  2553        0.8
2554 2025-12-29  2554       -2.8
2555 2025-12-30  2555        1.6
2556 2025-12-31  2556       -7.7

In [3]:
df['Radians_Angle'] = (df['Step'] * -(2 * np.pi / (365))) -4.70
df

           Date  Step  Value_Pct  Radians_Angle
0    2019-01-01     0        1.5      -4.700000
1    2019-01-02     1       -0.2      -4.717214
2    2019-01-03     2        2.3      -4.734428
3    2019-01-04     3        5.1      -4.751643
4    2019-01-05     4       -0.0      -4.768857
...         ...   ...        ...            ...
2552 2025-12-27  2552        5.1     -48.630655
2553 2025-12-28  2553        0.8     -48.647869
2554 2025-12-29  2554       -2.8     -48.665083
2555 2025-12-30  2555        1.6     -48.682297
2556 2025-12-31  2556       -7.7     -48.699511

[2557 rows x 4 columns]

In [4]:
df['Radius'] = (df['Step'] * 0.15) + (df['Value_Pct'] * 1.5)
df

           Date  Step  Value_Pct  Radians_Angle  Radius
0    2019-01-01     0        1.5      -4.700000    2.25
1    2019-01-02     1       -0.2      -4.717214   -0.15
2    2019-01-03     2        2.3      -4.734428    3.75
3    2019-01-04     3        5.1      -4.751643    8.10
4    2019-01-05     4       -0.0      -4.768857    0.60
...         ...   ...        ...            ...     ...
2552 2025-12-27  2552        5.1     -48.630655  390.45
2553 2025-12-28  2553        0.8     -48.647869  384.15
2554 2025-12-29  2554       -2.8     -48.665083  378.90
2555 2025-12-30  2555        1.6     -48.682297  385.65
2556 2025-12-31  2556       -7.7     -48.699511  371.85

[2557 rows x 5 columns]

In [5]:
df['x'] = df['Radius'] * np.cos(df['Radians_Angle'])
df['y'] = df['Radius'] * np.sin(df['Radians_Angle'])
df['Entry_Type'] = "SpiralData"

In [6]:
df_gl = df[["Step", "Radians_Angle"]].copy()
df_gl['Radius'] = df_gl['Step'] * 0.15
df_gl['x'] = df_gl['Radius'] * np.cos(df_gl['Radians_Angle'])
df_gl['y'] = df_gl['Radius'] * np.sin(df_gl['Radians_Angle'])
df_gl['Entry_Type'] = "SpiralGuide"
df_gl

      Step  Radians_Angle  Radius          x           y   Entry_Type
0        0      -4.700000    0.00  -0.000000    0.000000  SpiralGuide
1        1      -4.717214    0.15   0.000724    0.149998  SpiralGuide
2        2      -4.734428    0.30   0.006611    0.299927  SpiralGuide
3        3      -4.751643    0.45   0.017660    0.449653  SpiralGuide
4        4      -4.768857    0.60   0.033863    0.599044  SpiralGuide
...    ...            ...     ...        ...         ...          ...
2552  2552     -48.630655  382.80 -24.494550  382.015519  SpiralGuide
2553  2553     -48.647869  382.95 -17.922172  382.530389  SpiralGuide
2554  2554     -48.665083  383.10 -11.339324  382.932148  SpiralGuide
2555  2555     -48.682297  383.25  -4.747955  383.220588  SpiralGuide
2556  2556     -48.699511  383.40   1.849984  383.395537  SpiralGuide

[2557 rows x 6 columns]

In [7]:
step = df_gl['Step'].values[-1]
radians = df_gl['Radians_Angle'].values[-1]
radius = df_gl['Radius'].values[-1]
last_x = df_gl['x'].values[-1]
last_y = df_gl['y'].values[-1]

[step, radians, radius, 2_100, last_y, "SpiralGuide"]
df_gl

      Step  Radians_Angle  Radius          x           y   Entry_Type
0        0      -4.700000    0.00  -0.000000    0.000000  SpiralGuide
1        1      -4.717214    0.15   0.000724    0.149998  SpiralGuide
2        2      -4.734428    0.30   0.006611    0.299927  SpiralGuide
3        3      -4.751643    0.45   0.017660    0.449653  SpiralGuide
4        4      -4.768857    0.60   0.033863    0.599044  SpiralGuide
...    ...            ...     ...        ...         ...          ...
2552  2552     -48.630655  382.80 -24.494550  382.015519  SpiralGuide
2553  2553     -48.647869  382.95 -17.922172  382.530389  SpiralGuide
2554  2554     -48.665083  383.10 -11.339324  382.932148  SpiralGuide
2555  2555     -48.682297  383.25  -4.747955  383.220588  SpiralGuide
2556  2556     -48.699511  383.40   1.849984  383.395537  SpiralGuide

[2557 rows x 6 columns]

In [8]:
df = pd.concat([df, df_gl], ignore_index= True)
df

,Date,Step,Value_Pct,Radians_Angle,Radius,x,y,Entry_Type
0,2019-01-01,0,1.5,-4.700000,2.25,-0.027874,2.249827,SpiralData
1,2019-01-02,1,-0.2,-4.717214,-0.15,-0.000724,-0.149998,SpiralData
2,2019-01-03,2,2.3,-4.734428,3.75,0.082641,3.749089,SpiralData
3,2019-01-04,3,5.1,-4.751643,8.10,0.317873,8.093760,SpiralData
4,2019-01-05,4,-0.0,-4.768857,0.60,0.033863,0.599044,SpiralData
...,...,...,...,...,...,...,...,...
5109,NaT,2552,NaN,-48.630655,382.80,-24.494550,382.015519,SpiralGuide
5110,NaT,2553,NaN,-48.647869,382.95,-17.922172,382.530389,SpiralGuide
5111,NaT,2554,NaN,-48.665083,383.10,-11.339324,382.932148,SpiralGuide
5112,NaT,2555,NaN,-48.682297,383.25,-4.747955,383.220588,SpiralGuide
5113,NaT,2556,NaN,-48.699511,383.40,1.849984,383.395537,SpiralGuide

In [9]:
df.to_csv('spiral_chart_vals_orientation.csv', index=False)